# Generated by Django 6.0.7 on 2026-07-13 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LimiteOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pacientes_adicionales', models.IntegerField(default=0, help_text='Tope adicional de pacientes')),
                ('citas_adicionales_mes', models.IntegerField(default=0, help_text='Tope adicional de citas al mes')),
                ('notas', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_expiracion', models.DateField(blank=True, help_text='Fecha de vencimiento del beneficio (opcional)', null=True)),
                ('nutricionista', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='override_limite', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Override de Límite',
                'verbose_name_plural': 'Overrides de Límites',
            },
        ),
    ]
