# Generated by Django 6.0.7 on 2026-07-13 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_perfilnutricionista_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilnutricionista',
            name='rol',
            field=models.CharField(choices=[('nutricionista', 'Nutricionista'), ('admin_plataforma', 'Administrador de Plataforma')], default='nutricionista', max_length=30, verbose_name='Rol'),
        ),
    ]
