# Generated by Django 6.0.7 on 2026-07-18 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_perfilnutricionista_dni_perfilnutricionista_ruc'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilnutricionista',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/fotos/', verbose_name='Foto de perfil'),
        ),
    ]
