# Generated by Django 6.0.6 on 2026-06-22 17:04

import pacientes.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0005_alter_paciente_dni'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='talla',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estatura inicial o de referencia del paciente', max_digits=5, null=True, validators=[pacientes.validators.validate_talla], verbose_name='Talla (cm)'),
        ),
    ]
