# Generated by Django 6.0.6 on 2026-06-22 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0006_paciente_talla'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='edad',
            field=models.IntegerField(blank=True, null=True, verbose_name='Edad'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='imc_clasificacion',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Clasificación IMC'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='imc_inicial',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='IMC Inicial'),
        ),
    ]
