# Generated by Django 6.0.5 on 2026-06-22 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0007_paciente_edad_paciente_imc_clasificacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='informacion_clinica',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Información Clínica y Hábitos'),
        ),
    ]
