# Generated by Django 6.0.6 on 2026-06-23 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0008_paciente_informacion_clinica'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='evaluacion',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Evaluación Nutricional'),
        ),
    ]
