# Generated by Django 6.0.6 on 2026-06-23 03:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0009_paciente_evaluacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanAlimentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Plan Alimentario Basal', max_length=200)),
                ('calorias', models.PositiveIntegerField(default=2000)),
                ('proteinas', models.PositiveIntegerField(default=150)),
                ('carbohidratos', models.PositiveIntegerField(default=200)),
                ('grasas', models.PositiveIntegerField(default=65)),
                ('fibra', models.PositiveIntegerField(default=25)),
                ('agua_recomendada', models.DecimalField(decimal_places=1, default=2.5, max_digits=3)),
                ('estado', models.CharField(choices=[('Borrador', 'Borrador'), ('Activo', 'Activo'), ('Finalizado', 'Finalizado'), ('Suspendido', 'Suspendido')], default='Borrador', max_length=20)),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('comidas', models.JSONField(blank=True, default=list)),
                ('sustituciones', models.JSONField(blank=True, default=list)),
                ('recomendaciones', models.JSONField(blank=True, default=list)),
                ('suplementacion', models.JSONField(blank=True, default=list)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_alimentarios_sync', to='pacientes.paciente')),
            ],
            options={
                'verbose_name': 'Plan Alimentario Sync',
                'verbose_name_plural': 'Planes Alimentarios Sync',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
