# Generated by Django 6.0.6 on 2026-06-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0010_planalimentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='seguimiento',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Seguimiento Nutricional'),
        ),
    ]
