# Generated by Django 6.0.6 on 2026-06-27 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0011_paciente_seguimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='planalimentario',
            name='tipo_plan',
            field=models.CharField(default='Estándar', max_length=100),
        ),
    ]
