# Generated by Django 6.0.6 on 2026-06-27 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0012_planalimentario_tipo_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='planalimentario',
            name='enviado_al_paciente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='planalimentario',
            name='fecha_envio',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
