# Generated by Django 6.0.6 on 2026-06-27 20:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0013_planalimentario_enviado_al_paciente_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del Archivo')),
                ('archivo', models.FileField(upload_to='pacientes/archivos/', verbose_name='Archivo')),
                ('categoria', models.CharField(choices=[('Documentos', 'Documentos'), ('Laboratorios', 'Laboratorios'), ('Fotos de Progreso', 'Fotos de Progreso'), ('Informes', 'Informes'), ('Otros', 'Otros')], max_length=50, verbose_name='Categoría')),
                ('subcategoria', models.CharField(blank=True, max_length=100, verbose_name='Subcategoría')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Carga')),
                ('nutricionista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos_subidos', to=settings.AUTH_USER_MODEL, verbose_name='Profesional Responsable')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='pacientes.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Archivo de Paciente',
                'verbose_name_plural': 'Archivos de Pacientes',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
