# Generated by Django 6.0.6 on 2026-07-11 08:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0005_cita_nutricionista_alter_cita_estado_and_more'),
        ('pacientes', '0014_archivopaciente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_consulta', models.PositiveIntegerField(verbose_name='Número de consulta')),
                ('tipo', models.CharField(choices=[('primera_consulta', 'Primera consulta'), ('seguimiento', 'Seguimiento'), ('reevaluacion', 'Reevaluación'), ('control', 'Control'), ('deportiva', 'Consulta deportiva'), ('clinica', 'Consulta clínica'), ('otro', 'Otro')], default='seguimiento', max_length=50, verbose_name='Tipo de consulta')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('hora_inicio', models.TimeField(default=django.utils.timezone.now, verbose_name='Hora de inicio')),
                ('hora_fin', models.TimeField(blank=True, null=True, verbose_name='Hora de fin')),
                ('estado', models.CharField(choices=[('en_curso', 'En curso'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='en_curso', max_length=20, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones de la consulta')),
                ('informacion_clinica', models.JSONField(blank=True, default=dict, null=True, verbose_name='Información Clínica de la Consulta')),
                ('evaluacion', models.JSONField(blank=True, default=dict, null=True, verbose_name='Evaluación y Diagnóstico de la Consulta')),
                ('seguimiento', models.JSONField(blank=True, default=dict, null=True, verbose_name='Seguimiento de la Consulta')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas', to='citas.cita', verbose_name='Cita originaria')),
                ('consulta_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas_siguientes', to='pacientes.consulta', verbose_name='Consulta anterior')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='pacientes.paciente', verbose_name='Paciente')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas_atendidas', to=settings.AUTH_USER_MODEL, verbose_name='Nutricionista')),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
                'ordering': ['paciente', 'numero_consulta'],
                'unique_together': {('paciente', 'numero_consulta')},
            },
        ),
        migrations.AddField(
            model_name='archivopaciente',
            name='consulta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archivos', to='pacientes.consulta', verbose_name='Consulta'),
        ),
        migrations.AddField(
            model_name='planalimentario',
            name='consulta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planes_alimentarios', to='pacientes.consulta'),
        ),
    ]
