# Generated by Django 6.0.7 on 2026-07-17 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0017_merge_20260711_2059'),
        ('pacientes', '0020_alter_archivopaciente_archivo'),
    ]

    operations = [
    ]
