# Generated by Django 6.0.7 on 2026-07-17 08:40

from django.db import migrations


def actualizar_descripcion(apps, schema_editor):
    PlanSuscripcion = apps.get_model("facturacion", "PlanSuscripcion")
    try:
        plan = PlanSuscripcion.objects.get(nombre="Enterprise")
        plan.descripcion = "Sin límites. Para nutricionistas que necesitan todo el poder de NutriSync."
        plan.save()
    except PlanSuscripcion.DoesNotExist:
        pass


def revertir_descripcion(apps, schema_editor):
    PlanSuscripcion = apps.get_model("facturacion", "PlanSuscripcion")
    try:
        plan = PlanSuscripcion.objects.get(nombre="Enterprise")
        plan.descripcion = "Sin límites. Para nutricionistas y clínicas que necesitan todo el poder de NutriSync."
        plan.save()
    except PlanSuscripcion.DoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0007_alter_cobro_cita_alter_cobro_metodo_pago_usado_and_more'),
    ]

    operations = [
        migrations.RunPython(actualizar_descripcion, revertir_descripcion),
    ]

