# Generated by Django 6.0.7 on 2026-07-11 06:45

import django.db.models.deletion
import nutricion.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutricion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=150, verbose_name='Nombre de la receta')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('instrucciones', models.JSONField(blank=True, default=list, help_text="Lista de pasos en formato JSON (ej: ['Paso 1', 'Paso 2'])", verbose_name='Instrucciones de preparación')),
                ('tiempo_preparacion', models.PositiveIntegerField(default=15, help_text='Tiempo total estimado de preparación en minutos', validators=[nutricion.validators.validate_tiempo_preparacion], verbose_name='Tiempo de preparación (min)')),
                ('porciones', models.PositiveIntegerField(default=1, help_text='Número de porciones que rinde la receta', validators=[nutricion.validators.validate_porciones], verbose_name='Porciones')),
                ('es_sistema', models.BooleanField(default=False, help_text='Marcar si es una receta predeterminada y compartida para todos', verbose_name='Receta del sistema')),
                ('imagen_predeterminada', models.CharField(default='salad', help_text='Nombre de la ilustración a renderizar (ej: salad, soup, chicken, dessert)', max_length=50, verbose_name='Imagen predeterminada')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Receta',
                'verbose_name_plural': 'Recetas',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='comidaplan',
            name='recetas_sugeridas',
            field=models.ManyToManyField(blank=True, related_name='comidas_plan', to='nutricion.receta', verbose_name='Recetas sugeridas'),
        ),
        migrations.CreateModel(
            name='IngredienteReceta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=1, help_text='Cantidad exacta en gramos (g)', max_digits=6, validators=[nutricion.validators.validate_cantidad_ingrediente], verbose_name='Cantidad (g)')),
                ('nota', models.CharField(blank=True, help_text='Ej: 1 taza, picada en cubos, opcional', max_length=150, verbose_name='Nota / Medida casera')),
                ('alimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes_recetas', to='nutricion.alimento', verbose_name='Alimento')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes', to='nutricion.receta', verbose_name='Receta')),
            ],
            options={
                'verbose_name': 'Ingrediente de Receta',
                'verbose_name_plural': 'Ingredientes de Receta',
                'unique_together': {('receta', 'alimento')},
            },
        ),
    ]
