# Generated by Django 6.0.7 on 2026-07-11 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutricion', '0002_receta_comidaplan_recetas_sugeridas_and_more'),
        ('pacientes', '0014_archivopaciente'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='paciente',
            field=models.ForeignKey(blank=True, help_text='Dejar en blanco si es una plantilla de receta global.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recetas_especificas', to='pacientes.paciente', verbose_name='Paciente específico'),
        ),
    ]
