# Generated by Django 6.0.5 on 2026-05-21 06:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('citas', '0001_initial'),
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedidaCorporal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de medición')),
                ('peso_kg', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)], verbose_name='Peso (kg)')),
                ('talla_cm', models.DecimalField(decimal_places=1, max_digits=5, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(250)], verbose_name='Talla (cm)')),
                ('imc', models.DecimalField(decimal_places=1, editable=False, help_text='Calculado automáticamente: peso / (talla en m)²', max_digits=4, verbose_name='IMC')),
                ('grasa_corporal_pct', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Grasa corporal (%)')),
                ('cintura_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(200)], verbose_name='Cintura (cm)')),
                ('cadera_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(200)], verbose_name='Cadera (cm)')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medidas', to='pacientes.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Medida Corporal',
                'verbose_name_plural': 'Medidas Corporales',
                'ordering': ['-fecha', '-fecha_registro'],
                'indexes': [models.Index(fields=['paciente', 'fecha'], name='seguimiento_pacient_900d52_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotaClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('contenido', models.TextField(verbose_name='Contenido')),
                ('tipo', models.CharField(choices=[('consulta', 'Consulta'), ('seguimiento', 'Seguimiento'), ('observacion', 'Observación'), ('receta', 'Receta')], default='consulta', max_length=20, verbose_name='Tipo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('cita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas', to='citas.cita', verbose_name='Cita relacionada')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_clinicas', to='pacientes.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Nota Clínica',
                'verbose_name_plural': 'Notas Clínicas',
                'ordering': ['-fecha', '-fecha_creacion'],
                'indexes': [models.Index(fields=['paciente', 'tipo'], name='seguimiento_pacient_7bb272_idx')],
            },
        ),
    ]
