# Generated by Django 6.0.6 on 2026-06-22 19:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medidacorporal',
            name='agua_corporal_pct',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Agua corporal (%)'),
        ),
        migrations.AddField(
            model_name='medidacorporal',
            name='brazo_cm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(100)], verbose_name='Brazo (cm)'),
        ),
        migrations.AddField(
            model_name='medidacorporal',
            name='cuello_cm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(150)], verbose_name='Cuello (cm)'),
        ),
        migrations.AddField(
            model_name='medidacorporal',
            name='grasa_visceral',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)], verbose_name='Grasa visceral'),
        ),
        migrations.AddField(
            model_name='medidacorporal',
            name='masa_grasa_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)], verbose_name='Masa grasa (kg)'),
        ),
        migrations.AddField(
            model_name='medidacorporal',
            name='masa_muscular_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)], verbose_name='Masa muscular (kg)'),
        ),
        migrations.AddField(
            model_name='medidacorporal',
            name='masa_muscular_pct',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='% masa muscular'),
        ),
        migrations.AddField(
            model_name='medidacorporal',
            name='masa_osea_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)], verbose_name='Masa ósea (kg)'),
        ),
        migrations.AddField(
            model_name='medidacorporal',
            name='muslo_cm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(150)], verbose_name='Muslo (cm)'),
        ),
        migrations.AddField(
            model_name='medidacorporal',
            name='pantorrilla_cm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(100)], verbose_name='Pantorrilla (cm)'),
        ),
        migrations.AddField(
            model_name='medidacorporal',
            name='pecho_cm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(250)], verbose_name='Pecho (cm)'),
        ),
        migrations.AddField(
            model_name='medidacorporal',
            name='peso_objetivo_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)], verbose_name='Peso objetivo (kg)'),
        ),
        migrations.AddField(
            model_name='medidacorporal',
            name='tmb',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(10000)], verbose_name='Tasa metabólica basal (TMB)'),
        ),
    ]
