# Generated by Django 6.0.6 on 2026-07-11 08:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0005_cita_nutricionista_alter_cita_estado_and_more'),
        ('pacientes', '0014_archivopaciente'),
        ('seguimiento', '0002_medidacorporal_agua_corporal_pct_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recomendacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=50, verbose_name='Categoría')),
                ('descripcion', models.JSONField(blank=True, default=dict, verbose_name='Descripción/Detalles')),
                ('fecha', models.DateField(verbose_name='Fecha de recomendación')),
                ('estado_cumplimiento', models.CharField(choices=[('pendiente', 'Pendiente'), ('cumplida', 'Cumplida'), ('parcial', 'Parcialmente cumplida'), ('no_cumplida', 'No cumplida')], default='pendiente', max_length=20, verbose_name='Estado de Cumplimiento')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('cita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recomendaciones', to='citas.cita', verbose_name='Consulta / Cita')),
                ('nutricionista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomendaciones_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Profesional responsable')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomendaciones', to='pacientes.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Recomendación',
                'verbose_name_plural': 'Recomendaciones',
                'ordering': ['-fecha', '-fecha_registro'],
            },
        ),
    ]
