# Generated by Django 6.0.6 on 2026-07-11 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0005_cita_nutricionista_alter_cita_estado_and_more'),
        ('pacientes', '0014_archivopaciente'),
        ('seguimiento', '0003_recomendacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entregable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('plan_alimentario', 'Plan Alimentario'), ('recomendaciones', 'Recomendaciones'), ('reporte', 'Reporte de Evolución'), ('material_educativo', 'Material Educativo'), ('lista_compras', 'Lista de Compras'), ('resumen_consulta', 'Resumen de Consulta')], max_length=50, verbose_name='Tipo')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('fecha_publicacion', models.DateField(verbose_name='Fecha de publicación')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('publicado', 'Publicado'), ('archivado', 'Archivado')], default='borrador', max_length=20, verbose_name='Estado')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='entregables/', verbose_name='Archivo o recurso asociado')),
                ('recurso_asociado', models.JSONField(blank=True, default=dict, verbose_name='Metadatos de recurso asociado')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('cita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregables', to='citas.cita', verbose_name='Consulta / Cita')),
                ('nutricionista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregables_creados', to=settings.AUTH_USER_MODEL, verbose_name='Profesional responsable')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregables', to='pacientes.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Entregable',
                'verbose_name_plural': 'Entregables',
                'ordering': ['-fecha_publicacion', '-fecha_registro'],
            },
        ),
    ]
