# Generated by Django 6.0.6 on 2026-07-11 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0015_consulta_archivopaciente_consulta_and_more'),
        ('seguimiento', '0004_entregable'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregable',
            name='consulta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregables_consulta', to='pacientes.consulta', verbose_name='Consulta'),
        ),
        migrations.AddField(
            model_name='medidacorporal',
            name='consulta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medidas_corporales', to='pacientes.consulta', verbose_name='Consulta'),
        ),
        migrations.AddField(
            model_name='notaclinica',
            name='consulta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_clinicas_consulta', to='pacientes.consulta', verbose_name='Consulta'),
        ),
        migrations.AddField(
            model_name='recomendacion',
            name='consulta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recomendaciones_consulta', to='pacientes.consulta', verbose_name='Consulta'),
        ),
    ]
