# Generated by Django 6.0.7 on 2026-07-17 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0008_alter_entregable_cita_alter_notaclinica_cita_and_more'),
        ('seguimiento', '0008_alter_notaclinica_tipo'),
    ]

    operations = [
    ]
