# Generated by Django 6.0.7 on 2026-07-18 08:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0009_merge_20260717_0345'),
    ]

    operations = [
        migrations.AddField(
            model_name='notaclinica',
            name='adherencia_plan',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Nivel de adherencia al plan (1-10)'),
        ),
        migrations.AddField(
            model_name='notaclinica',
            name='calidad_sueno',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Calidad del sueño (1-5)'),
        ),
        migrations.AddField(
            model_name='notaclinica',
            name='marcadores_bioquimicos',
            field=models.TextField(blank=True, verbose_name='Apuntes de laboratorio / Exámenes'),
        ),
        migrations.AddField(
            model_name='notaclinica',
            name='nivel_energia',
            field=models.IntegerField(blank=True, help_text='1: Muy bajo, 5: Excelente', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Nivel de energía (1-5)'),
        ),
        migrations.AddField(
            model_name='notaclinica',
            name='recordatorio_24h',
            field=models.TextField(blank=True, verbose_name='Recordatorio de 24 horas / Ingesta típica'),
        ),
        migrations.AddField(
            model_name='notaclinica',
            name='sintomas_gastrointestinales',
            field=models.TextField(blank=True, verbose_name='Síntomas gastrointestinales (Ej. inflamación, tránsito)'),
        ),
        migrations.AddField(
            model_name='notaclinica',
            name='suplementacion_actual',
            field=models.TextField(blank=True, verbose_name='Suplementación y medicación actual'),
        ),
    ]
